# Generated by Django 6.0.2 on 2026-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hightea',
            name='message',
        ),
        migrations.AddField(
            model_name='hightea',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Availabe', 'Available'), ('Null', 'Null')], default='Available', max_length=20),
        ),
    ]
