# Generated by Django 6.0.2 on 2026-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_hightea_status_payment_hightea_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='sponsor_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='sunday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
